spring:
  application:
    name: ${SPRING_APP_NAME:ewgf-backend-development}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/Tekken-Database}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:guest}
  config:
    activate:
      on-profile: !prod  # Activates when NOT in prod profile
    import: optional:docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: ${HIBERNATE_BATCH_SIZE:1000}
        order_inserts: true
        order_updates: true
  output:
    ansi:
      enabled: ALWAYS

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE_NAME:battle_queue}
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME:battle_exchange}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:battle.routingkey}
  management:
    api:
      url: ${RABBITMQ_API_URL:http://localhost:15672/api}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    vhost: ${RABBITMQ_VHOST:/}

concurrency:
  rabbitmq: ${RABBITMQ_CONCURRENCY:4}

backpressure:
  threshold: ${BACKPRESSURE_THRESHOLD:50}
  slowdown:
    factor: ${BACKPRESSURE_SLOWDOWN_FACTOR:10}

wavu:
  api: ${WAVU_API:https://wank.wavu.wiki/api/replays}

security:
  rate-limit:
    requests-per-window: ${RATE_LIMIT_REQUESTS:20}
    window-minutes: ${RATE_LIMIT_WINDOW:1}
    cleanup-interval-ms: ${RATE_LIMIT_CLEANUP_MS:3600000}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
    max-age-seconds: ${CORS_MAX_AGE:3600}

logging:
  level:
    org:
      ewgf:
        controllers:
          PlayerController: INFO
          AggregatedStatisticController: INFO
        services:
          WavuService: INFO
          RabbitService: INFO
        configuration:
          BackpressureManager: INFO