CREATE TABLE aggregated_statistics
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_version  INTEGER,
    character_id  VARCHAR(255),
    dan_rank      INTEGER,
    total_wins    INTEGER,
    total_losses  INTEGER,
    total_players INTEGER,
    total_replays INTEGER,
    category      VARCHAR(255),
    computed_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_aggregated_statistics PRIMARY KEY (id)
);

ALTER TABLE past_player_names
    ADD CONSTRAINT pk_past_player_names PRIMARY KEY (id);

ALTER TABLE past_player_names
    ADD CONSTRAINT uc_7065f1ddd5e8513184a0bdc31 UNIQUE (name);

DROP TABLE enums CASCADE;

ALTER TABLE character_stats
    DROP COLUMN rating;

ALTER TABLE battles
    DROP COLUMN version;

ALTER TABLE players
    DROP COLUMN version;

ALTER TABLE battles
    ALTER COLUMN battle_at SET NOT NULL;

ALTER TABLE past_player_names
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE past_player_names
    ALTER COLUMN player_id SET NOT NULL;